export const theme = {
  source: '#9a00cdff',
  schemes: {
    light: {
      primary: '#9a00cdff',
      onPrimary: '#ffffffff',
      primaryContainer: '#f9d8ffff',
      onPrimaryContainer: '#320046ff',
      secondary: '#00629dff',
      onSecondary: '#ffffffff',
      secondaryContainer: '#cfe5ffff',
      onSecondaryContainer: '#001d33ff',
      tertiary: '#006a64ff',
      onTertiary: '#ffffffff',
      tertiaryContainer: '#71f7edff',
      onTertiaryContainer: '#00201eff',
      error: '#ba1a1aff',
      onError: '#ffffffff',
      errorContainer: '#ffdad6ff',
      onErrorContainer: '#410002ff',
      background: '#fffbffff',
      onBackground: '#1e1b1eff',
      surface: '#fffbffff',
      onSurface: '#1e1b1eff',
      surfaceVariant: '#ebdfe9ff',
      onSurfaceVariant: '#4c444dff',
      outline: '#7d747dff',
      outlineVariant: '#cfc3cdff',
      shadow: '#000000ff',
      scrim: '#000000ff',
      inverseSurface: '#332f33ff',
      inverseOnSurface: '#f7eff3ff',
      inversePrimary: '#edb1ffff',
      primaryContainerOpacity10: 'rgba(117, 0, 157, 0.1)',
      primaryContainerOpacity20: 'rgba(117, 0, 157, 0.2)',
      primaryContainerOpacity40: 'rgba(117, 0, 157, 0.4)',
      onPrimaryContainerOpacity10: 'rgba(117, 0, 157, 0.1)',
      onPrimaryContainerOpacity20: 'rgba(117, 0, 157, 0.2)',
      onPrimaryContainerOpacity40: 'rgba(117, 0, 157, 0.4)',
      surface1: 'linear-gradient(0deg, rgba(154, 0, 205, 0.05), rgba(154, 0, 205, 0.05)), #FFFBFF',
      surface2: 'linear-gradient(0deg, rgba(154, 0, 205, 0.08), rgba(154, 0, 205, 0.08)), #FFFBFF',
      surface3: 'linear-gradient(0deg, rgba(154, 0, 205, 0.11), rgba(154, 0, 205, 0.11)), #FFFBFF',
      surface4: 'linear-gradient(0deg, rgba(154, 0, 205, 0.12), rgba(154, 0, 205, 0.12)), #FFFBFF',
      surface5: 'linear-gradient(0deg, rgba(154, 0, 205, 0.14), rgba(154, 0, 205, 0.14)), #FFFBFF',
      depth1: '#F4F1FD',
      depth2: '#F2F3FE',
      depth3: '#F3F6FF',
      depth4: '#F7FAFF',
      bodyBackground: '#ffffffff',
    },
    dark: {
      primary: '#edb1ffff',
      onPrimary: '#530070ff',
      primaryContainer: '#75009dff',
      onPrimaryContainer: '#f9d8ffff',
      secondary: '#99cbffff',
      onSecondary: '#003354ff',
      secondaryContainer: '#004a78ff',
      onSecondaryContainer: '#cfe5ffff',
      tertiary: '#4fdbd1ff',
      onTertiary: '#003734ff',
      tertiaryContainer: '#00504cff',
      onTertiaryContainer: '#71f7edff',
      error: '#ffb4abff',
      onError: '#690005ff',
      errorContainer: '#93000aff',
      onErrorContainer: '#ffb4abff',
      background: '#1e1b1eff',
      onBackground: '#e8e0e5ff',
      surface: '#1e1b1eff',
      onSurface: '#e8e0e5ff',
      surfaceVariant: '#4c444dff',
      onSurfaceVariant: '#cfc3cdff',
      outline: '#988e97ff',
      outlineVariant: '#4c444dff',
      shadow: '#000000ff',
      scrim: '#000000ff',
      inverseSurface: '#e8e0e5ff',
      inverseOnSurface: '#332f33ff',
      inversePrimary: '#9a00cdff',
      primaryContainerOpacity10: 'rgba(117, 0, 157, 0.1)',
      primaryContainerOpacity20: 'rgba(117, 0, 157, 0.2)',
      primaryContainerOpacity40: 'rgba(117, 0, 157, 0.4)',
      onPrimaryContainerOpacity10: 'rgba(249, 216, 255, 0.1)',
      onPrimaryContainerOpacity20: 'rgba(249, 216, 255, 0.2)',
      onPrimaryContainerOpacity40: 'rgba(249, 216, 255, 0.4)',
      surface1:
        'linear-gradient(0deg, rgba(237, 177, 255, 0.05), rgba(237, 177, 255, 0.05)), #1E1B1E',
      surface2:
        'linear-gradient(0deg, rgba(237, 177, 255, 0.08), rgba(237, 177, 255, 0.08)), #1E1B1E',
      surface3:
        'linear-gradient(0deg, rgba(237, 177, 255, 0.11), rgba(237, 177, 255, 0.11)), #1E1B1E',
      surface4:
        'linear-gradient(0deg, rgba(237, 177, 255, 0.12), rgba(237, 177, 255, 0.12)), #1E1B1E',
      surface5:
        'linear-gradient(0deg, rgba(237, 177, 255, 0.14), rgba(237, 177, 255, 0.14)), #1E1B1E',
      depth1: '#262228',
      depth2: '#242127',
      depth3: '#221F26',
      depth4: '#211F25',
      bodyBackground: '#000000ff',
    },
  },
  palettes: {
    primary: {
      hue: 321.23522734798786,
      chroma: 84.89838592576614,
      cache: {},
    },
    secondary: {
      hue: 321.23522734798786,
      chroma: 16,
      cache: {},
    },
    tertiary: {
      hue: 381.23522734798786,
      chroma: 24,
      cache: {},
    },
    neutral: {
      hue: 321.23522734798786,
      chroma: 4,
      cache: {},
    },
    neutralVariant: {
      hue: 321.23522734798786,
      chroma: 8,
      cache: {},
    },
    error: {
      hue: 25,
      chroma: 84,
      cache: {},
    },
  },
  typography: {
    en: {
      display: {
        large: {
          fontFamily: 'Noto Sans',
          fontSize: '3.5625rem',
          lineHeight: '4rem',
          fontWeight: 500,
        },
        medium: {
          fontFamily: 'Noto Sans',
          fontSize: '2.8125rem',
          lineHeight: '3.25rem',
          fontWeight: 500,
        },
        small: {
          fontFamily: 'Noto Sans',
          fontSize: '2.25rem',
          lineHeight: '2,75rem',
          fontWeight: 600,
        },
      },
      headLine: {
        large: {
          fontFamily: 'Noto Sans',
          fontSize: '2rem',
          lineHeight: '2.5rem',
          fontWeight: 600,
        },
        medium: {
          fontFamily: 'Noto Sans',
          fontSize: '1.75rem',
          lineHeight: '2.25rem',
          fontWeight: 600,
        },
        small: {
          fontFamily: 'Noto Sans',
          fontSize: '1.5rem',
          lineHeight: '2rem',
          fontWeight: 600,
        },
      },
      title: {
        exLarge: {
          fontFamily: 'Noto Sans',
          fontSize: '1.375rem',
          lineHeight: '1.75rem',
          fontWeight: 500,
        },
        large: {
          fontFamily: 'Noto Sans',
          fontSize: '1.125rem',
          lineHeight: '1.5625rem',
          fontWeight: 600,
        },
        medium: {
          fontFamily: 'Noto Sans',
          fontSize: '1rem',
          lineHeight: '1.4375rem',
          fontWeight: 600,
        },
        small: {
          fontFamily: 'Noto Sans',
          fontSize: '0.875rem',
          lineHeight: '1.25rem',
          fontWeight: 600,
        },
      },
      label: {
        large: {
          fontFamily: 'Noto Sans',
          fontSize: '0.875rem',
          lineHeight: '1.25rem',
          fontWeight: 600,
        },
        medium: {
          fontFamily: 'Noto Sans',
          fontSize: '0.75rem',
          lineHeight: '1rem',
          fontWeight: 500,
        },
        small: {
          fontFamily: 'Noto Sans',
          fontSize: '0.6875rem',
          lineHeight: '1rem',
          fontWeight: 600,
        },
      },
      body: {
        large: {
          fontFamily: 'Noto Sans',
          fontSize: '1rem',
          lineHeight: '1.5rem',
          fontWeight: 400,
        },
        medium: {
          fontFamily: 'Noto Sans',
          fontSize: '0.875rem',
          lineHeight: '1.25rem',
          fontWeight: 400,
        },
        small: {
          fontFamily: 'Noto Sans',
          fontSize: '0.75rem',
          lineHeight: '1rem',
          fontWeight: 500,
        },
      },
      bodyBold: {
        large: {
          fontFamily: 'Noto Sans',
          fontSize: '1rem',
          lineHeight: '1.5rem',
          fontWeight: 700,
        },
        medium: {
          fontFamily: 'Noto Sans',
          fontSize: '0.875rem',
          lineHeight: '1.25rem',
          fontWeight: 700,
        },
        small: {
          fontFamily: 'Noto Sans',
          fontSize: '0.75rem',
          lineHeight: '1rem',
          fontWeight: 700,
        },
      },
    },
    jp: {
      display: {
        large: {
          fontFamily: 'Noto Sans',
          fontSize: '3.125rem',
          lineHeight: '4rem',
          fontWeight: 700,
        },
        medium: {
          fontFamily: 'Noto Sans',
          fontSize: '2.50rem',
          lineHeight: '3.25rem',
          fontWeight: 500,
        },
        small: {
          fontFamily: 'Noto Sans',
          fontSize: '1.875rem',
          lineHeight: '2,75rem',
          fontWeight: 600,
        },
      },
      headLine: {
        large: {
          fontFamily: 'Noto Sans',
          fontSize: '1.625rem',
          lineHeight: '2.5rem',
          fontWeight: 700,
        },
        medium: {
          fontFamily: 'Noto Sans',
          fontSize: '1.375rem',
          lineHeight: '2.25rem',
          fontWeight: 700,
        },
        small: {
          fontFamily: 'Noto Sans',
          fontSize: '1.25rem',
          lineHeight: '2rem',
          fontWeight: 700,
        },
      },
      title: {
        exLarge: {
          fontFamily: 'Noto Sans',
          fontSize: '1.25rem',
          lineHeight: '1.75rem',
          fontWeight: 500,
        },
        large: {
          fontFamily: 'Noto Sans',
          fontSize: '1.0625rem',
          lineHeight: '1.5625rem',
          fontWeight: 600,
        },
        medium: {
          fontFamily: 'Noto Sans',
          fontSize: '0.9375rem',
          lineHeight: '1.4375rem',
          fontWeight: 600,
        },
        small: {
          fontFamily: 'Noto Sans',
          fontSize: '0.8125rem',
          lineHeight: '1.25rem',
          fontWeight: 600,
        },
      },
      label: {
        large: {
          fontFamily: 'Noto Sans',
          fontSize: '0.8125rem',
          lineHeight: '1.25rem',
          fontWeight: 700,
        },
        medium: {
          fontFamily: 'Noto Sans',
          fontSize: '0.6875rem',
          lineHeight: '1rem',
          fontWeight: 700,
        },
        small: {
          fontFamily: 'Noto Sans',
          fontSize: '0.625rem',
          lineHeight: '1rem',
          fontWeight: 700,
        },
      },
      body: {
        large: {
          fontFamily: 'Noto Sans',
          fontSize: '0.9375rem',
          lineHeight: '1.5rem',
          fontWeight: 400,
        },
        medium: {
          fontFamily: 'Noto Sans',
          fontSize: '0.875rem',
          lineHeight: '1.25rem',
          fontWeight: 400,
        },
        small: {
          fontFamily: 'Noto Sans',
          fontSize: '0.75rem',
          lineHeight: '1rem',
          fontWeight: 500,
        },
      },
      bodyBold: {
        large: {
          fontFamily: 'Noto Sans',
          fontSize: '0.9375rem',
          lineHeight: '1.5rem',
          fontWeight: 700,
        },
        medium: {
          fontFamily: 'Noto Sans',
          fontSize: '0.875rem',
          lineHeight: '1.25rem',
          fontWeight: 700,
        },
        small: {
          fontFamily: 'Noto Sans',
          fontSize: '0.75rem',
          lineHeight: '1rem',
          fontWeight: 900,
        },
      },
    },
  },
  customColors: [],
}
