export type ColorProps = 'dominant' | 'subdominant' | 'neutral' | 'error' | 'success'
export type SizeProps = 'sm' | 'md' | 'lg'
export type VariantProps = 'filled' | 'tonal' | 'outlined' | 'text'
export type Placement =
  | 'bottom'
  | 'bottom left'
  | 'bottom right'
  | 'bottom start'
  | 'bottom end'
  | 'top'
  | 'top left'
  | 'top right'
  | 'top start'
  | 'top end'
  | 'left'
  | 'left top'
  | 'left bottom'
  | 'start'
  | 'start top'
  | 'start bottom'
  | 'right'
  | 'right top'
  | 'right bottom'
  | 'end'
  | 'end top'
  | 'end bottom'
